package:
  name: coral
  version: 2.3.21

source: 
  fn: coral-CORAL_2_3_21-cms32.tar.gz
  url: file:///home/zhen/cmsrepo/coral-CORAL_2_3_21-cms32.tar.gz

requirements: 
  run: 
    - libstdcplus
    - boost
    - xerces-c
    - frontier_client
    - oracle



